name: wb_env
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - xarray
  - netCDF4
  - pandas
  - geopandas
  - scikit-image
  - scipy
  - tqdm
  - shapely >= 2.0.1
  - scikit-learn
# for plotting
  - matplotlib
  - cartopy >= 0.21.1
# for testing
  - pip
  - flake8
  - tox
# for readthedocs
  - sphinx_rtd_theme
