name: wb_env
channels:
  - conda-forge
dependencies:
  - xarray
  - netCDF4
  - pandas
  - geopandas
  - scikit-image
  - scipy
  - tqdm
  - shapely
  - scikit-learn
  - matplotlib
  - cartopy
# for testing
  - pip
  - flake8
  - tox
